project_id = "azrfvjecmcloaqidrspi"

[functions.tmdb]
verify_jwt = false

[functions.real-debrid]
verify_jwt = false

[functions.categorize-media]
verify_jwt = false

[functions.torrentio]
verify_jwt = false

[functions.stream-check]
verify_jwt = false

[functions.stream-proxy]
verify_jwt = true
